# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    config.vm.box = "ubuntu/bionic64"
    web.vm.network "private_network", ip: "192.168.33.10"
    web.vm.network "public_network", ip: "192.168.33.40"
    web.vm.network "forwarded_port", guest: 80, host: 80
    web.vm.provision "shell", inline: <<-SHELL
      echo "webserver" > /etc/hostname
      hostname -b webserver
      echo "192.168.33.20          appserver" >> /etc/hosts
      sudo apt-get install -y apache2
    SHELL
  end

  config.vm.define "gateway" do |gateway|
    config.vm.box = "ubuntu/bionic64"
    gateway.vm.network "private_network", ip: "192.168.33.20"
    gateway.vm.network "forwarded_port", guest: 3000, host: 3000
    gateway.vm.provision "shell", inline: <<-SHELL
      echo "gatewayserver" > /etc/hostname
      hostname -b gatewayserver
      echo "192.168.33.10          webserver" >> /etc/hosts
      echo "192.168.33.30          dbserver" >> /etc/hosts
    SHELL
  end

  config.vm.define "db" do |db|
    config.vm.box = "ubuntu/bionic64"
    db.vm.network "private_network", ip: "192.168.33.30"
    db.vm.network "forwarded_port", guest: 3030, host: 3030
    db.vm.provision "shell", inline: <<-SHELL
      echo "dbserver" > /etc/hostname
      hostname -b dbserver
      echo "192.168.33.10          webserver" >> /etc/hosts
      sudo apt-get install -y mysql-server
    SHELL
  end
end



